zookeeper:
  image: jplock/zookeeper:3.4.6

kafka:
  image: ches/kafka
  links:
    - zookeeper
  ports:
    - 9092

engine:
  build: cmd/engine
  volumes:
    - ./web:/web
  links:
    - kafka
  ports:
    - 2000:8080
  environment:
    WEB_PATH: "/web"
    KAFKA_ADDR: "kafka:9092"
    SSL: "false"
    PORT: ":8080"
    TLS_PORT:
    CERTIFICATE:
    KEY:
